### ISSUE TITLE
symfony3

### ISSUE THREAD

**Issue by ami-m** [jasvrcek/IcsBundle#3]
are there any plans to make the bundle ready for symfony3

**Comment by jasvrcek** [comment]
Hi @ami-m, are you getting a specific error with a version of Symfony3?

**Comment by ami-m** [comment]
I'm currently on symfony 2.8, collecting deprecation notices.
There are a few, mostly about not quoting scalar values with a @ sign in the service definitions.

I haven't collected them yet as I have many (many) bundles to check in my project.
But if you plan on making the bundle symfony3 ready, I'll be more than happy to compile a list of all the deprecation notices I have :-)

**Comment by jasvrcek** [comment]
Yes, please send them!

**Comment by ami-m** [comment]
Sorry for the delay in answering. 

`
The "scope" attribute of service "jsvrcek_ics.export" in file ".../vendor/jsvrcek/ics-bundle/Jsvrcek/Bundle/IcsBundle/DependencyInjection/../Resources/config/services.xml" is deprecated since version 2.8 and will be removed in 3.0.
`
and similar messages for these services:
 - jsvrcek_ics.export
 - jsvrcek_ics.stream
 - jsvrcek_ics.utility.formatter
 - jsvrcek_ics.model.calendar
 - jsvrcek_ics.model.calendar_alarm
 - jsvrcek_ics.model.calendar_event
 - jsvrcek_ics.model.calendar_free_busy
 - jsvrcek_ics.model.calendar_todo
 - jsvrcek_ics.model.relationship.attendee
 - jsvrcek_ics.model.relationship.organizer
 - jsvrcek_ics.model.description.geo
 - jsvrcek_ics.model.description.location

**Comment by GenieTim** [comment]
#4

**Comment by jasvrcek** [comment]
Closing, @BernhardWebstudio fixed in #4

**Comment by GenieTim** [comment]
Thank you very much for merging, @jasvrcek . Out of curiosity: How exactly does this work with composer - will it recognize the new version automatically, when refreshing some cache, or do you have to submit it specifically?

**Comment by jasvrcek** [comment]
@BernhardWebstudio I believe composer should grab the latest commit if you have the version set to "dev-master" in your project composer.json, and you then run `composer update jsvrcek/ics-bundle`

**Comment by GenieTim** [comment]
Thank you for your answer @jasvrcek !
